# Generated by Django 4.2.5 on 2023-09-22 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Показатель метрики',
                'verbose_name_plural': 'Показатели метрики',
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_within_normal_range', models.BooleanField(default=True)),
                ('indicator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicators')),
            ],
            options={
                'verbose_name': 'Результат измерения',
                'verbose_name_plural': 'Результаты измерений',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('comment', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.labs')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('indicator_metric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.indicatormetric')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.tests')),
            ],
            options={
                'verbose_name': 'Количественное значение',
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField()),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labs')),
                ('measurement_results', models.ManyToManyField(related_name='research_results', to='api.measurementresult')),
            ],
            options={
                'verbose_name': 'Результат исследования',
                'verbose_name_plural': 'Результаты исследований',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('indicator_metric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.indicatormetric')),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
            },
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='metric_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_results_name', to='api.metrics'),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='metric_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_results_unit', to='api.metrics'),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scores'),
        ),
        migrations.AddField(
            model_name='indicatormetric',
            name='indicator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_metrics', to='api.indicators'),
        ),
        migrations.AddField(
            model_name='indicatormetric',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_metrics', to='api.metrics'),
        ),
    ]
